version: "3.9"

services:
  db:
    image: postgres:18
    container_name: webcrud-db
    restart: always
    environment:
      POSTGRES_USER: ondickson
      POSTGRES_PASSWORD: ondickson
      POSTGRES_DB: webcrud
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: webcrud-redis
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webcrud-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      JWT_SECRET: change_this_for_prod
      DATABASE_URL: postgresql://ondickson:ondickson@db:5432/webcrud?schema=public
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis

volumes:
  db_data:
